<? /** @var Zend_View $this */ ?>
<style>

</style>
<div id="page">
    <h1>Курсы валют</h1>

    <div id="currencyContainer">
        <div class="currencyBlock">
                <?= $this->formSelect('currencySelectFirst', '', [], $this->currencies) ?>
            <div class="currencyShowFirst"></div>
        </div>
        <div class="currencyBlock">
            <div class="currencyShowSecond"></div>
        </div>
    </div>
</div>
<script>
    var currencyManager = function () {};
</script>