<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
    <title>Курсы валют</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="application/xhtml+xml; charset=utf-8"/>
<!--    --><?php //echo $this->headScript()->appendFile('js/jquery-2.1.4.min.js') ?>
<!--    --><?php //echo $this->headLink()->appendStylesheet('/css/main.css') ?>
    <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
</head>
<body>
<div id="page">
    <h1>Курсы валют</h1>
    <?php echo $this->layout()->content; ?>
</div>
</body>
</html>